language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ree
  - jruby

gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: ree
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: ree
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails-4.1.x
  fast_finish: true
