
# thepista.local
ENV['RECAPTCHA_PUBLIC_KEY'] = '6LfhKAgAAAAAAOzho3sELOcG-PkiPRBOX94ZrmEg'
ENV['RECAPTCHA_PRIVATE_KEY'] = '6LfhKAgAAAAAAAivbLUYGmNpdRwKQJL57V8I53o0'

# thepista.heroku.com
ENV['RECAPTCHA_PUBLIC_KEY'] = "6LfiKAgAAAAAAHRhcX9WTEdGbXW9B3hlFbea1RZZ" 
ENV['RECAPTCHA_PRIVATE_KEY'] = "6LfiKAgAAAAAABzbnVm1Km4oWJU6FsKqJaEtjuVa"  

# haypista.com
ENV['RECAPTCHA_PUBLIC_KEY'] = "6Ldb0AgAAAAAALIECSwKwI5y8FOWJQJZy9-muqUf"   
ENV['RECAPTCHA_PRIVATE_KEY'] = "6Ldb0AgAAAAAAPEgdSpUXhMFakV_NTOaIExPPD9Y"  
