# review peepcode-code-review.pdf
# to access the configuration settings 
# for the current environment with a simple lookup:

# APP_CONFIG['flickr_api']['key']

# thepista.local
development: 
    google_api:
        key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohQcuuUAALNd07C6qfGBYEYuSAyTnhR7YxsrQg3X4P7h718oyo40Ap6xiQ
    
    rpx_api: 
        key:            f7bbfeed95a9e71fe994397d496614da8972aa2c
        realm:          thepista-local

# http://thepista.heroku.com/
test:
    google_api:
        key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohSq-oAE0ua8qdLg2ooJ1gPBC3o68hSzsTAi3Ohp8MXoYZjPHRLMnqEGxw
    
    rpx_api: 
        key:            59b7bd4a615a2c17439b6a4ca064a1d5f482944e
        realm:          thepista-heroku 

# http://thepista.heroku.com/
staging:
    google_api:
        key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohSq-oAE0ua8qdLg2ooJ1gPBC3o68hSzsTAi3Ohp8MXoYZjPHRLMnqEGxw
    
    rpx_api: 
        key:            59b7bd4a615a2c17439b6a4ca064a1d5f482944e
        realm:          thepista-heroku

               
production:
    # haypista.heroku.com
    # google_api:
    #     key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohR-Y432UtzrUQVcRgSh7RX82w7ExxTMQ8-qK9OoHHqeTAR2GKavcStcyg             
    
    # rpx_api: 
        # key:            bcd9944176260aba26f0e1a9475f51160ac3eaf3
        # realm:          haypista-heroku
    
    # haypista.com
    google_api:
    key:                ABQIAAAACEstwoTkWwNQXJRd_oxlohRJsBlthpMFqyH8uqiMijHv-RMFmBTkGqR7rVuhstoeKCeFz7pjFx3ieA             
    
    rpx_api: 
        key:   2acf2c6b39e3d1d988629e0cb41c675827c2f45e
        realm: haypista