# # APP_CONFIG['rpx_api_realm']
# 
# # thepista.local
# development: 
#     google_api:
#         key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohSUSx-MY4mDXI31yLoG3nSQfTBNrhQlx595OTo0JB9r-YrOsXEpb_ut0A
#         
#     server_name: 
#         key:            thepista.dev
#         
#     bit_ly_api:
#         login:          haypista
#         key:            R_e843b4e8c994a59c71b10d54c319e23b
# 
#     disqus:
#         secret_key:  JKdz3WgZFZq7lmfV1whprURJk8QjIgVX6jV2LIqubmLvkbpLmZPfRlPWTm9Hg7YD
# 
#     yahoo:
#         app_id: 4uSWOoTV34EAizCZbcobagFpBQVErwkVJwnS8OUagpua3nJpKtTcfNr16X9yOIo-
# 
#     pubhub:    
#         publish_key: pub-4a29a03a-6f61-461f-a21b-75c61f73b55f
#         subscribe_key:  sub-2f610f4c-a98d-11e0-a8dc-f9b6701e4370
#         secret_key:  sec-ecc86188-966a-473c-9bc0-bb0ae1f33227
#             
#     pusher:
#         app_id:     '6771'
#         key:        'afb05b8322614fad0a71'
#         secret:     'fb1a66006db46476d0cc'
#         
#     linkedin:
#         api_key:        bMT6ozAQuigLB3B0rRvthjUdVucw9KaPmst3SI9-Ph6KPG9-T6Og5LGvcWF6hqS8
#         secret_key:     hWzelp5eIWkFX6wUTID6Dj3ljYnq6pTATQyYwtljCnH-azO4PJ1__N1nOThE-5fg
#         access_1_key:   05984f88-e096-4fae-8f2d-13915bf87f4f
#         access_2_key:   8c4b59f5-6046-4155-8c4a-44a4d80e791a
# 
# # http://thepista.heroku.com/
# test:
#     google_api:
#         key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohSq-oAE0ua8qdLg2ooJ1gPBC3o68hSzsTAi3Ohp8MXoYZjPHRLMnqEGxw
#         
#     server_name: 
#         key:            thepista.heroku.com
#         
#     bit_ly_api:
#         login:          haypista
#         key:            R_e843b4e8c994a59c71b10d54c319e23b
# 
#     disqus:
#         secret_key:  JKdz3WgZFZq7lmfV1whprURJk8QjIgVX6jV2LIqubmLvkbpLmZPfRlPWTm9Hg7YD
#     
#     yahoo:
#         app_id: 4uSWOoTV34EAizCZbcobagFpBQVErwkVJwnS8OUagpua3nJpKtTcfNr16X9yOIo-
#     
#     pubhub:    
#         publish_key: pub-4a29a03a-6f61-461f-a21b-75c61f73b55f
#         subscribe_key:  sub-2f610f4c-a98d-11e0-a8dc-f9b6701e4370
#         secret_key:  sec-ecc86188-966a-473c-9bc0-bb0ae1f33227
#             
#     pusher:
#         app_id:     '6771'
#         key:        'afb05b8322614fad0a71'
#         secret:     'fb1a66006db46476d0cc'
#         
#     linkedin:
#         api_key:        bMT6ozAQuigLB3B0rRvthjUdVucw9KaPmst3SI9-Ph6KPG9-T6Og5LGvcWF6hqS8
#         secret_key:     hWzelp5eIWkFX6wUTID6Dj3ljYnq6pTATQyYwtljCnH-azO4PJ1__N1nOThE-5fg
#         access_1_key:   05984f88-e096-4fae-8f2d-13915bf87f4f
#         access_2_key:   8c4b59f5-6046-4155-8c4a-44a4d80e791a
# 
# # http://thepista.heroku.com/
# staging:
#     google_api:
#         key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohSq-oAE0ua8qdLg2ooJ1gPBC3o68hSzsTAi3Ohp8MXoYZjPHRLMnqEGxw
#         
#     server_name: 
#         key:            thepista.heroku.com
#         
#     bit_ly_api:
#         login:          haypista
#         key:            R_e843b4e8c994a59c71b10d54c319e23b
# 
#     disqus:
#         secret_key:  JKdz3WgZFZq7lmfV1whprURJk8QjIgVX6jV2LIqubmLvkbpLmZPfRlPWTm9Hg7YD
#     
#     yahoo:
#         app_id: 4uSWOoTV34EAizCZbcobagFpBQVErwkVJwnS8OUagpua3nJpKtTcfNr16X9yOIo-
# 
#     pubhub:    
#         publish_key: pub-4a29a03a-6f61-461f-a21b-75c61f73b55f
#         subscribe_key:  sub-2f610f4c-a98d-11e0-a8dc-f9b6701e4370
#         secret_key:  sec-ecc86188-966a-473c-9bc0-bb0ae1f33227
#             
#     pusher:
#         app_id:     '6771'
#         key:        'afb05b8322614fad0a71'
#         secret:     'fb1a66006db46476d0cc'
#         
#     linkedin:
#         api_key:        bMT6ozAQuigLB3B0rRvthjUdVucw9KaPmst3SI9-Ph6KPG9-T6Og5LGvcWF6hqS8
#         secret_key:     hWzelp5eIWkFX6wUTID6Dj3ljYnq6pTATQyYwtljCnH-azO4PJ1__N1nOThE-5fg
#         access_1_key:   05984f88-e096-4fae-8f2d-13915bf87f4f
#         access_2_key:   8c4b59f5-6046-4155-8c4a-44a4d80e791a
# 
# # haypista.heroku.com
# production:
#     google_api:
#         key:            ABQIAAAACEstwoTkWwNQXJRd_oxlohRJsBlthpMFqyH8uqiMijHv-RMFmBTkGqR7rVuhstoeKCeFz7pjFx3ieA            
#         
#     server_name: 
#         key:            haypista.com
#         
#     bit_ly_api:
#         login:          haypista
#         key:            R_e843b4e8c994a59c71b10d54c319e23b
# 
#     disqus:
#         secret_key:  JKdz3WgZFZq7lmfV1whprURJk8QjIgVX6jV2LIqubmLvkbpLmZPfRlPWTm9Hg7YD
#     
#     yahoo:
#         app_id: 4uSWOoTV34EAizCZbcobagFpBQVErwkVJwnS8OUagpua3nJpKtTcfNr16X9yOIo-
#     
#     pubhub:    
#         publish_key: pub-4a29a03a-6f61-461f-a21b-75c61f73b55f
#         subscribe_key:  sub-2f610f4c-a98d-11e0-a8dc-f9b6701e4370
#         secret_key:  sec-ecc86188-966a-473c-9bc0-bb0ae1f33227
#             
#     pusher:
#         app_id:     '6771'
#         key:        'afb05b8322614fad0a71'
#         secret:     'fb1a66006db46476d0cc'
#         
#     linkedin:
#         api_key:        bMT6ozAQuigLB3B0rRvthjUdVucw9KaPmst3SI9-Ph6KPG9-T6Og5LGvcWF6hqS8
#         secret_key:     hWzelp5eIWkFX6wUTID6Dj3ljYnq6pTATQyYwtljCnH-azO4PJ1__N1nOThE-5fg
#         access_1_key:   05984f88-e096-4fae-8f2d-13915bf87f4f
#         access_2_key:   8c4b59f5-6046-4155-8c4a-44a4d80e791a