# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: desarrollo_thepista
  host: localhost
  pool: 5
  username: xxxxx
  password: xxxxx
  min_messages: warning
 
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: thepista_test
#   pool: 5
#   username: thepista
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: thepista_production
#   pool: 5
#   username: thepista
#   password:
