# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: desarrollo_thepista
  pool: 5
  username: johnny
  #password: 72dae4
  min_messages: warning
 
test:
  adapter: postgresql
  encoding: unicode
  database: thepista_test
  pool: 5
  username: johnny
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: thepista_production
  pool: 5
  username: johnny
  password:
