development:
  login: 'raulmp_1308504683_biz_api1.gmail.com'
  password: '1308504692'
  signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AEhy4Ky1dOMe7W5n8hrUF5zlgF6b'
production:
  login: 'raulmp_1308504683_biz_api1.gmail.com'
  password: '1308504692'
  signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AEhy4Ky1dOMe7W5n8hrUF5zlgF6b'
test:
  login: 'raulmp_1308504683_biz_api1.gmail.com'
  password: '1308504692'
  signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AEhy4Ky1dOMe7W5n8hrUF5zlgF6b'
