language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: "bundle exec rake coverage"
before_install:
  - gem install bundler
notifications:
  email:
    - michael+geokit@noack.com.au
